# Generated by Django 4.2.8 on 2023-12-12 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Register'},
        ),
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='user', max_length=255)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.register')),
            ],
            options={
                'verbose_name': 'Role',
                'db_table': 'Role',
            },
        ),
    ]
