# Generated by Django 4.2.8 on 2023-12-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('otp', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'OTP',
                'db_table': 'OTP',
            },
        ),
    ]
