# Generated by Django 4.2.8 on 2023-12-21 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_blog_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='')),
                ('uid', models.CharField(db_index=True, max_length=15)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.blog')),
            ],
        ),
    ]
