# Generated by Django 4.2.8 on 2023-12-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_role_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
