# Generated by Django 4.2.8 on 2023-12-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_remove_blogimages_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimages',
            name='uid',
            field=models.CharField(db_index=True, default=12345, max_length=15),
            preserve_default=False,
        ),
    ]
