# Generated by Django 4.2.8 on 2023-12-16 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_alter_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d+$', 'Enter a valid number.')]),
        ),
    ]
