# Generated by Django 4.2.8 on 2023-12-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_blogimages_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimages',
            name='uid',
        ),
    ]
