# Generated by Django 4.2.8 on 2023-12-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_article_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.TextField(),
        ),
    ]
