# Generated by Django 4.2.8 on 2023-12-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_alter_article_headline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='blog',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'blog'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='blog',
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
    ]
